import { cn } from "@/lib/utils";
import { STATE_LABEL, type MemberState } from "@/lib/membership/rules";

/** One color per standing, used everywhere a membership state is shown. */
export const STATE_TONE: Record<MemberState | "UPCOMING", string> = {
  ACTIVE: "bg-success/12 text-success ring-success/25",
  EXPIRING: "bg-warning/15 text-amber-700 ring-warning/30 dark:text-amber-300",
  EXPIRED: "bg-destructive/10 text-destructive ring-destructive/20",
  PENDING: "bg-info/12 text-info ring-info/25",
  CANCELLED: "bg-muted text-muted-foreground ring-border",
  NONE: "bg-muted text-muted-foreground ring-border",
  UPCOMING: "bg-info/12 text-info ring-info/25",
};

export function MemberStateBadge({ state, className }: { state: MemberState | "UPCOMING"; className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md px-1.5 py-0.5 text-xs font-medium whitespace-nowrap ring-1 ring-inset",
        STATE_TONE[state],
        className,
      )}
    >
      <span className="size-1.5 rounded-full bg-current" />
      {STATE_LABEL[state]}
    </span>
  );
}

/** Server-rendered SVG markup from `qrSvg()` — trusted, generated by us. */
export function QrImage({ svg, label, className }: { svg: string; label: string; className?: string }) {
  return (
    <div
      role="img"
      aria-label={label}
      className={cn("aspect-square overflow-hidden rounded-lg bg-white p-2 [&>svg]:size-full", className)}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
